project:
  type: book

book:
  title: "Exercises Hydrological Modelling"
  subtitle: "Academic year: 2025 - 2026"
  author: 
    - name: Olivier Bonte
      affiliation: Ghent University
      email: olivier.bonte@ugent.be  
    - name: Hans Lievens
      affiliation: Ghent University
      email: hans.lievens@ugent.be
  date: today
  downloads: [pdf]
  repo-url: https://github.com/olivierbonte/quarto_template_ugent
  navbar: 
    title: "Exercises Hydrological Modelling"
    search: true 
    logo: "figures/logo_H-CEL_no_background.svg"
  chapters:
    - index.qmd
    - practical_info.qmd
    - study_area_and_data.qmd
    - 1_catchment_delineation.qmd
    - 2_model_implementation.qmd
    - 3_model_calibration.qmd
    - 4_model_uncertainty.qmd
    - 5_data_assimilation.qmd
    - references.qmd
number-sections: true

bibliography: references.bib
jupyter: python3

format:
  html:
    theme:
      - cosmo
      - brand
    code-overflow: wrap
    code-fold: show
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex

# Allows caching of notebooks when previewing 
execute:
  cache: true
  freeze: auto

editor:
  render-on-save: true
