name: hydromod_env
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - jupyterlab=4.4
  - matplotlib=3.10
  - numpy=2.4
  - geopandas=1.1
  - rioxarray=0.22
  - jupyter-cache=1.0
  - owslib=0.35
  - loguru=0.7
  - pip
  - pip:
    - rootutils==1.0.*
    - pywaterinfo[cache]==0.9.*