# Study area and data {#sec-study-area}

```{python}
# | echo: false
# | output: false
import rootutils
import contextily as cx
import pandas as pd
import geopandas as gpd
import geodatasets as gds
import matplotlib.pyplot as plt
from scripts.data_process.conf import (
    FORCINGS_DISCHARGE_PROCESSED_DIR,
    CATCHMENT_INFO_PROCESSED_DIR,
    FILENAME_FORCINGS_DISCHARGE,
)
from scripts.data_download.conf import FILENAME_VHA
from shapely.geometry import box


root_path = rootutils.find_root()
processed_data_dir = root_path / "data" / "processed"
```

```{python}
# | echo: false
# | output: false
# summary statistics Zwalm catchment
df_fd = pd.read_csv(
    FORCINGS_DISCHARGE_PROCESSED_DIR / FILENAME_FORCINGS_DISCHARGE,
    index_col=0,
    parse_dates=True,
)
yearly_sums = df_fd.groupby(df_fd.index.year).sum()
yearly_mean = yearly_sums.mean()
start_year = int(df_fd.index.year.min())
end_year = int(df_fd.index.year.max())
```

For these exercises, a hydrological dataset of the Zwalm catchment will be used. The Zwalm catchment is located in the center of Belgium and can be considered a medium-scale catchment. Its main tributary, the Zwalmbeek, is visualised in @fig-zwalmbeek. During the period `{python} start_year`-`{python} end_year`, a dataset of daily precipitation, potential evapotranspiration and discharge is at your disposal. The average annual rainfall and potential evapotranspiration of the catchment are `{python} f"{yearly_mean.precipitation:.0f}"` mm and `{python} f"{yearly_mean.potential_evapotranspiration:.0f}"` mm respectively, typical values for Belgium.

```{python}
# | echo: false
# | fig-cap: "The Zwalmbeek and its location within Belgium (CRS: EPSG:31370)."
# | label: fig-zwalmbeek

# Visualise the river of the Zwalm
# Following https://geopandas.org/en/stable/gallery/plotting_basemap_background.html
gdf_vha = gpd.read_file(CATCHMENT_INFO_PROCESSED_DIR / FILENAME_VHA)
gdf_zwalmbeek = gdf_vha[gdf_vha["NAAM"] == "Zwalmbeek"]

fig, ax = plt.subplots(figsize=(6.5, 5), constrained_layout=True)
gdf_zwalmbeek.plot(ax=ax)
cx.add_basemap(ax, source=cx.providers.CartoDB.Positron, crs=gdf_zwalmbeek.crs, zoom=12)
ax.set_xlabel("x [m]")
ax.set_ylabel("y [m]")

# Now adding an inset axis to show the location within Belgium
# Following https://geopandas.org/en/latest/gallery/inset_map.html
iax = ax.inset_axes([0.05, 0.5, 0.4, 0.4], xticks=[], yticks=[])
# get GeoDataFrame of Belgium from geodatasets
europe = gpd.read_file(gds.get_path("eurostat.nuts_rg_10m_2024_3035"))
country_level = 0  # only keep country level, not regions
country_code_belgium = "BE"
belgium = europe[
    (europe.CNTR_CODE == country_code_belgium) & (europe.LEVL_CODE == country_level)
].to_crs(gdf_zwalmbeek.crs)
belgium.plot(ax=iax, color="whitesmoke", edgecolor="black")
# Add bbox of Zwalm catchment on the inset map
minx, miny, maxx, maxy = gdf_zwalmbeek.total_bounds
bbox_zwalm = gpd.GeoSeries([box(minx, miny, maxx, maxy)], crs=gdf_zwalmbeek.crs)
bbox_zwalm.plot(ax=iax, color="none", edgecolor="red", linewidth=1.5)
```

All the data needed for this exercise is available on Ufora as `data.zip`. Download this file, unzip it and place the resulting `data` folder in the root of this repository (that means at the same level as e.g. `scripts`). 

Alternatively, you can download and process the data yourself by following the instructions in `scripts/data_download/README.md` and `scripts/data_process/README.md`.

## Catchment data

## Meteorological and discharge data

## Digital terrain model 
